language: php

matrix:
    include:
        - name: 7.1 (tests)
          php: '7.1'
          env:
              - INSTALL_COMMAND="composer install"

        - name: 7.2 (tests)
          php: '7.2'
          env:
              - INSTALL_COMMAND="composer install"

        - name: 7.2 (tests, lowest deps)
          php: '7.2'
          env:
              - INSTALL_COMMAND="composer update --prefer-lowest --prefer-stable"

        - name: nightly (tests)
          php: nightly
          env:
              - INSTALL_COMMAND="composer install"

install: ${INSTALL_COMMAND}

script: ./vendor/bin/phpunit --colors
